"""tensorgrad: a from-scratch deep-learning framework on top of NumPy.

The top-level namespace holds the :class:`Tensor` type, grad-mode switches, tensor factories
and every differentiable op. :mod:`tensorgrad.autograd` exposes the engine (``grad``,
``backward``), :mod:`tensorgrad.func` the function transforms (``grad``, ``vjp``, ``jvp``,
``jacobian``, ``hessian``, ``hvp``); neural-network layers live in :mod:`tensorgrad.nn`,
optimisers in :mod:`tensorgrad.optim` and gradient checking / data loading / checkpoints in
:mod:`tensorgrad.utils`. :mod:`tensorgrad.profiler` times ops and :mod:`tensorgrad.viz`
draws graphs.
"""

from tensorgrad import autograd, func, profiler, viz
from tensorgrad._random import get_rng, manual_seed
from tensorgrad.autograd import enable_grad, is_grad_enabled, no_grad
from tensorgrad.ops import (
    add,
    binary_cross_entropy_with_logits,
    broadcast_to,
    concat,
    conv2d,
    cross_entropy,
    div,
    dropout,
    embedding,
    exp,
    flatten,
    gelu,
    layer_norm,
    linear,
    log,
    log_softmax,
    logsumexp,
    masked_fill,
    matmul,
    max,
    max_pool2d,
    mean,
    min,
    mse_loss,
    mul,
    neg,
    permute,
    pow,
    relu,
    reshape,
    sigmoid,
    softmax,
    sqrt,
    squeeze,
    stack,
    sub,
    sum,
    tanh,
    transpose,
    unsqueeze,
    var,
    where,
)
from tensorgrad.tensor import (
    Tensor,
    arange,
    full,
    get_default_dtype,
    ones,
    ones_like,
    rand,
    randn,
    set_default_dtype,
    tensor,
    zeros,
    zeros_like,
)

__version__ = "0.2.0"

__all__ = [
    "Tensor",
    "__version__",
    "add",
    "arange",
    "autograd",
    "binary_cross_entropy_with_logits",
    "broadcast_to",
    "concat",
    "conv2d",
    "cross_entropy",
    "div",
    "dropout",
    "embedding",
    "enable_grad",
    "exp",
    "flatten",
    "full",
    "func",
    "gelu",
    "get_default_dtype",
    "get_rng",
    "is_grad_enabled",
    "layer_norm",
    "linear",
    "log",
    "log_softmax",
    "logsumexp",
    "manual_seed",
    "masked_fill",
    "matmul",
    "max",
    "max_pool2d",
    "mean",
    "min",
    "mse_loss",
    "mul",
    "neg",
    "no_grad",
    "ones",
    "ones_like",
    "permute",
    "pow",
    "profiler",
    "rand",
    "randn",
    "relu",
    "reshape",
    "set_default_dtype",
    "sigmoid",
    "softmax",
    "sqrt",
    "squeeze",
    "stack",
    "sub",
    "sum",
    "tanh",
    "tensor",
    "transpose",
    "unsqueeze",
    "var",
    "viz",
    "where",
    "zeros",
    "zeros_like",
]
